@Dsw2026Ej15.Api_HostAddress = http://localhost:5026

POST {{Dsw2026Ej15.Api_HostAddress}}/api/doctors
Content-Type: application/json

{
  "name": "Juan Perez",
  "licenseNumber": "MP1234",
  "specialityId": "8a1f3b78-3f66-4d68-8d6e-1c5b9c7a2f41"
}